name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the daos-dev image
      run: cd daos-dev && docker build . --file Dockerfile --tag daos-dev:rocky8.4
    - name: Build the Docker image (check if whole projects builds)
      run: docker build . --file Dockerfile --tag adb:$(date +%s)
